# Basic Information 
title: Yulya Zubak / Юля Зубак
position: Lab Manager, Social Interaction Lab
affiliation: University of Wisconsin-Madison
email: yzubak (at) wisc.edu 

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: yuliya zubak social interaction cognitive science psychology computational zeitgeist yulya 
baseurl: ""


# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=nLaI3iIAAAAJ&hl=en&oi=ao
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/zubyul
linkedin: https://www.linkedin.com/in/yuliya-zubak/
twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/photo.jpeg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon.png
header: ./assets/img/frame.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: UA-111540567-4


# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
